### ISSUE TITLE
"also" is not "so"

### ISSUE THREAD

**Issue by dylan-k** [errata-ai/write-good#2]
There may be a false positive for the word "also" in `So.yml`. The file looks for "so followed by a space" but this is also true when the word also is followed by a space. Perhaps, instead, it should look for "so preceded by a period and/or space(s)" and also look for  "so preceded by line break(s)"

Unfortunately I can read regex fairly well, but I'm unsure how to write it, or else I'd try my hand at a pull request.

**Comment by jdkato** [comment]
This shouldn't be an issue: we don't simply look for "so followed by a space"; it needs to be prefaced by either `(?:[;-]\s)` or `\b`.

See [this Regex101 session](https://regex101.com/r/weDaXq/1/) for a better explanation.
