### ISSUE TITLE
Illusions incorrectly flags lines

### ISSUE THREAD

**Issue by jessetan** [errata-ai/write-good#4]
Given the following rst:

```rst
foo foo

foo bar

foo ``bar`` foo bar

foo ``bar`` foo ``bar``

foo ``bar`` foo ``bar`` cows
```

The output is:
```
 1:1  warning  'foo' is repeated!  write-good.Illusions 
 5:1  warning  'foo' is repeated!  write-good.Illusions 
 7:1  warning  'foo' is repeated!  write-good.Illusions 
 9:1  warning  'foo' is repeated!  write-good.Illusions 
```

Expected output should only contain line 1. My guess is that vale removes the literal (the text between double backticks) before applying the regex.

Note that if you remove the empty lines, the output is different even though it should be the same.

**Comment by jdkato** [comment]
This has been fixed in [v0.3.2](https://github.com/errata-ai/write-good/releases/tag/v0.3.2).
