### ISSUE TITLE
"It's" missing from E-Prime?

### ISSUE THREAD

**Issue by tomato42** [errata-ai/write-good#5]
I can find "is" and "isn't" in E-Prime:
https://github.com/errata-ai/write-good/blob/769e957f492587dc90b9dfeb7bc29488bc733cfc/write-good/E-Prime.yml#L17-L18

but I don't see "it's". Shouldn't it be there?

**Comment by jdkato** [comment]
I would say *yes*, it should be included. However, the tool this style is based on ([write-good](https://github.com/Vorror/e-prime/blob/master/e-prime.js)) doesn't include it.

So, it becomes a question of whether or not we should deviate from the original implementation.

**Comment by tomato42** [comment]
Filed https://github.com/Vorror/e-prime/issues/2 to update it

Edit: and looks like it will be fixed upstream

**Comment by tomato42** [comment]
added in write-good: https://github.com/Vorror/e-prime/blob/6bc3bb4ccfd08198ce6950d83aba7695a4aff66d/e-prime.js#L15

**Comment by jdkato** [comment]
Fixed in ca93f38dd76765a17ca5d110f9cf3ca57e0ad9c1.

**Comment by tomato42** [comment]
thanks!
