### ISSUE TITLE
E-Prime false positive: be

### ISSUE THREAD

**Issue by pirj** [errata-ai/write-good#6]
`Try to avoid using 'be'.` is suggested for e.g. `before` and `best`.

**Comment by pirj** [comment]
Similar: `Try to avoid using 'am'.` for `amount`.

**Comment by jdkato** [comment]
I can't reproduce this -- could you share the full sentence / file of the false positive?

**Comment by pirj** [comment]
Sure, here you go:

```
37:218   suggestion  Try to avoid using 'be'.        write-good.E-Prime
37:233   suggestion  Try to avoid using 'be'.        write-good.E-Prime
```
Line 37:
>   Why? Answers to those questions come to you sooner or later when you join a company. And often times that truth is not something you can change or deal with. And have to change your employer, again. Some things are better to know before making a serious decision. If you are not primarily motivated by the salary, those questions are for you. They can reveal the factors that make your daily job a breeze, or a nightmare.

column 218 has `better`, column 233 has `before`.

```
# vale.ini
StylesPath = /Users/pirj/.local/share/vale

MinAlertLevel = suggestion

# Global settings (applied to every syntax)
[*]
BasedOnStyles = write-good
```

Using https://github.com/errata-ai/write-good/releases/latest/download/write-good.zip from a couple days ago. Unzipped it to /Users/pirj/.local/share/vale/write-good.

```
$ vale --version
vale version 2.1.1
```

**Comment by pirj** [comment]
If it does matter, [here's the file](https://github.com/pirj/pirj.github.io/blob/40db9f8127ba28dcfde06f8eb517d6e590d141ef/questions-to-ask-in-a-job-interview.html#L40). It doesn't seem to be the exactly the same revision it hiccups on, but the wording is roughly the same.

**Comment by jdkato** [comment]
This is a bug with Vale itself (not `write-good`) and it'll be fixed in the next release.

**Comment by pirj** [comment]
Good to know, thanks a lot!
